name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.4'

      - name: Build Release APK (module app)
        working-directory: ./app
        run: |
          gradle assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lightx-apk
          path: app/build/outputs/**/*.apk
